name: Garrett-GitHubActionsScheduled

on:
  schedule:
    - cron: '20 19 * * *'
    - cron: '30 23 * * *'
    - cron: '45 19 * * 1'  # Ejecutar los lunes a las 15:45 (UTC-4)
    - cron: '00 00 * * 1'  # Ejecutar los lunes a las 20:00 (UTC-4)
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout git
      uses: actions/checkout@v4

    - name: Pruebas React
      run: |
        echo "Corriendo pruebas React del proyecto..."
        echo "Pruebas completadas de manera satisfactoria!"

  build:  
    runs-on: ubuntu-20.04
    needs: [test]

    steps:
    - name: Checkout git
      uses: actions/checkout@v4
      
    - name: Dependencias y building
      run: |
        npm install
        npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - name: Checkout git
      uses: actions/checkout@v4

    - name: Deploy a produccion
      run: |
        echo "Deployando a produccion..."
        echo "Deploy completado de manera satisfactoria!"
