name: Garrett-GitHubActions

on:
  push:
    branches:
      - feature/*

  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout git
      uses: actions/checkout@v4

    - name: Pruebas React
      run: |
        echo "Corriendo pruebas React del proyecto..."
        echo "Pruebas completadas de manera satisfactoria!"

  build:  
    runs-on: ubuntu-20.04
    needs: [test]

    steps:
    - name: Checkout git
      uses: actions/checkout@v4
      
    - name: Dependencias y building
      run: |
        npm install
        npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - name: Checkout git
      uses: actions/checkout@v4

    - name: Deploy a produccion
      run: |
        echo "Deployando a produccion..."
        echo "Deploy completado de manera satisfactoria!"
